# **1. What is NumPy and why is it important in scientific computing?**

NumPy (Numerical Python) is a Python library for numerical computations.
It provides support for multi-dimensional arrays and high-performance mathematical functions.

# Advantages over Python lists:

Performance: NumPy arrays are much faster because they are implemented in C and store elements in contiguous memory blocks.

Memory Efficiency: NumPy arrays use less memory than Python lists because they store data in fixed-type arrays (all elements of the same type).

Vectorized Operations: Unlike lists, operations on arrays don’t require loops; NumPy applies operations to entire arrays at once.

# 2. Install and verify NumPy

In [ ]:
import numpy as np
print(np.__version__)


2.0.2


# 3. Create 1D and 2D arrays

In [ ]:
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print("arr1:", arr1)
print("Type:", type(arr1), "Shape:", arr1.shape, "dtype:", arr1.dtype, "Size:", arr1.size)

print("\narr2:\n", arr2)
print("Type:", type(arr2), "Shape:", arr2.shape, "dtype:", arr2.dtype, "Size:", arr2.size)


arr1: [1 2 3 4 5]
Type: <class 'numpy.ndarray'> Shape: (5,) dtype: int64 Size: 5

arr2:
 [[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'> Shape: (2, 3) dtype: int64 Size: 6


# 4. Generate arrays with NumPy functions

In [ ]:
print(np.zeros((4,4)))
           # 4x4 zeros
print(np.ones((2,6)))
              # 2x6 ones
print(np.arange(5, 55, 5))
          # 5 to 50 step 5
print(np.linspace(0, 5, 20))
       # 20 values evenly spaced


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[ 5 10 15 20 25 30 35 40 45 50]
[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]


# 5. Array slicing

In [ ]:
a = np.arange(20)

print(a[:7])       # first 7 elements
print(a[-5:])      # last 5 elements
print(a[::2])      # every second element
print(a[5:13])     # index 5 to 12


[0 1 2 3 4 5 6]
[15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18]
[ 5  6  7  8  9 10 11 12]


# 6. 3x3 matrix access

In [ ]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(mat[1,2])   # second row, third column
print(mat[0])     # first row
print(mat[:,2])   # last column


6
[1 2 3]
[3 6 9]


# 7. Reshape a 1D array

In [ ]:
arr = np.arange(16)

print(arr.reshape(4,4))   # (4x4)
print(arr.reshape(2,8))   # (2x8)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


# 8. Flatten and reshape back

In [ ]:
arr2D = np.array([[1,2,3],[4,5,6]])
flat = arr2D.flatten()
print(flat)

reshaped = flat.reshape(2,3)
print(reshaped)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# 9. Broadcasting example

In [ ]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

arr = np.array([10,20,30])
print(mat + arr)   # broadcast addition


[[11 22 33]
 [14 25 36]
 [17 28 39]]


# 10. Multiply rows with broadcasting

In [ ]:
mat = np.ones((4,4))
scalars = np.array([1,2,3,4]).reshape(4,1)  # reshape to column vector
print(mat * scalars)


[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


# 11. Element-wise operations

In [ ]:
x = np.array([10,20,30])
y = np.array([1,2,3])

print(x + y)
print(x - y)
print(x * y)
print(x / y)


[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


# 12. Discounts problem

In [ ]:
prices = np.array([100,200,300])
discounts = np.array([0.1,0.25,0.2])

final_prices = prices * (1 - discounts)
print(final_prices)


[ 90. 150. 240.]


# 13. Matrix operations

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Addition:\n", A+B)
print("Multiplication:\n", A@B)  # matrix multiplication
print("Transpose:\n", A.T)
print("Determinant:", np.linalg.det(A))


Addition:
 [[ 6  8]
 [10 12]]
Multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Determinant: -2.0000000000000004
